
import java.awt.*;

public class AskQuestion extends javax.swing.JDialog {

    private int[] playerScores;
    private boolean[] vectPressed;
    private boolean[] diffPressed;
    private boolean[] curvePressed;
    private boolean[] hopPressed;
    private boolean[] intPressed;
    private String questionType;
    private int ptsAdded;
    private int turn;
    private int numPlayers;
    
    private VectorQuestions vectQ;
    private DiffQuestions diffQ;
    private CurveQuestions curveQ;
    private LHopitalQuestions hopQ;
    private IntegrationQuestions intQ;
    
    /**
     * Creates new form AskQuestion
     */
    public AskQuestion(java.awt.Frame parent, boolean modal, int numPlayers, VectorQuestions vectQ, DiffQuestions diffQ, CurveQuestions curveQ, LHopitalQuestions hopQ, IntegrationQuestions intQ) {
        super(parent, modal);
        
        vectPressed = new boolean[5];
        diffPressed = new boolean[5];
        curvePressed = new boolean[5];
        hopPressed = new boolean[5];
        intPressed = new boolean[5];
        
        ptsAdded = 0;
        questionType = "";
        
        turn = 1;
        
        playerScores = new int[numPlayers];
        this.numPlayers = numPlayers;
        
        this.hopQ = hopQ;
        this.intQ = intQ;
        this.vectQ = vectQ;
        this.diffQ = diffQ;
        this.curveQ = curveQ;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        vect1 = new javax.swing.JButton();
        menuTitle = new javax.swing.JLabel();
        vect2 = new javax.swing.JButton();
        vect3 = new javax.swing.JButton();
        vect4 = new javax.swing.JButton();
        vect5 = new javax.swing.JButton();
        vectLabel = new javax.swing.JLabel();
        diff2 = new javax.swing.JButton();
        diff3 = new javax.swing.JButton();
        diff4 = new javax.swing.JButton();
        diffLabel = new javax.swing.JLabel();
        diff5 = new javax.swing.JButton();
        diff1 = new javax.swing.JButton();
        curve2 = new javax.swing.JButton();
        curve3 = new javax.swing.JButton();
        curve4 = new javax.swing.JButton();
        curveLabel = new javax.swing.JLabel();
        curve5 = new javax.swing.JButton();
        curve1 = new javax.swing.JButton();
        hop2 = new javax.swing.JButton();
        hop3 = new javax.swing.JButton();
        hop4 = new javax.swing.JButton();
        hopLabel = new javax.swing.JLabel();
        hop5 = new javax.swing.JButton();
        hop1 = new javax.swing.JButton();
        int2 = new javax.swing.JButton();
        int3 = new javax.swing.JButton();
        int4 = new javax.swing.JButton();
        intLabel = new javax.swing.JLabel();
        int5 = new javax.swing.JButton();
        int1 = new javax.swing.JButton();
        player1Label = new javax.swing.JTextField();
        player2Label = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionLabel = new javax.swing.JTextArea();
        help = new javax.swing.JButton();
        restart = new javax.swing.JButton();
        creditsLabel = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculus Jeopardy");
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(java.awt.Color.lightGray);

        vect1.setBackground(new java.awt.Color(6, 12, 223));
        vect1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect1.setForeground(new java.awt.Color(255, 255, 255));
        vect1.setText("100");
        vect1.setBorder(null);
        vect1.setBorderPainted(false);
        vect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect1ActionPerformed(evt);
            }
        });

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("Calculus Jeopardy");
        menuTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vect2.setBackground(new java.awt.Color(6, 12, 223));
        vect2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect2.setForeground(new java.awt.Color(255, 255, 255));
        vect2.setText("200");
        vect2.setBorder(null);
        vect2.setBorderPainted(false);
        vect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect2ActionPerformed(evt);
            }
        });

        vect3.setBackground(new java.awt.Color(6, 12, 223));
        vect3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect3.setForeground(new java.awt.Color(255, 255, 255));
        vect3.setText("300");
        vect3.setBorder(null);
        vect3.setBorderPainted(false);
        vect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect3ActionPerformed(evt);
            }
        });

        vect4.setBackground(new java.awt.Color(6, 12, 223));
        vect4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect4.setForeground(new java.awt.Color(255, 255, 255));
        vect4.setText("400");
        vect4.setBorder(null);
        vect4.setBorderPainted(false);
        vect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect4ActionPerformed(evt);
            }
        });

        vect5.setBackground(new java.awt.Color(6, 12, 223));
        vect5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect5.setForeground(new java.awt.Color(255, 255, 255));
        vect5.setText("500");
        vect5.setBorder(null);
        vect5.setBorderPainted(false);
        vect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect5ActionPerformed(evt);
            }
        });

        vectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vectLabel.setText("Vectors");

        diff2.setBackground(new java.awt.Color(6, 12, 223));
        diff2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff2.setForeground(new java.awt.Color(255, 255, 255));
        diff2.setText("200");
        diff2.setBorder(null);
        diff2.setBorderPainted(false);
        diff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff2ActionPerformed(evt);
            }
        });

        diff3.setBackground(new java.awt.Color(6, 12, 223));
        diff3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff3.setForeground(new java.awt.Color(255, 255, 255));
        diff3.setText("300");
        diff3.setBorder(null);
        diff3.setBorderPainted(false);
        diff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff3ActionPerformed(evt);
            }
        });

        diff4.setBackground(new java.awt.Color(6, 12, 223));
        diff4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff4.setForeground(new java.awt.Color(255, 255, 255));
        diff4.setText("400");
        diff4.setBorder(null);
        diff4.setBorderPainted(false);
        diff4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff4ActionPerformed(evt);
            }
        });

        diffLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffLabel.setText("Differentiation");

        diff5.setBackground(new java.awt.Color(6, 12, 223));
        diff5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff5.setForeground(new java.awt.Color(255, 255, 255));
        diff5.setText("500");
        diff5.setBorder(null);
        diff5.setBorderPainted(false);
        diff5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff5ActionPerformed(evt);
            }
        });

        diff1.setBackground(new java.awt.Color(6, 12, 223));
        diff1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff1.setForeground(new java.awt.Color(255, 255, 255));
        diff1.setText("100");
        diff1.setBorder(null);
        diff1.setBorderPainted(false);
        diff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff1ActionPerformed(evt);
            }
        });

        curve2.setBackground(new java.awt.Color(6, 12, 223));
        curve2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve2.setForeground(new java.awt.Color(255, 255, 255));
        curve2.setText("200");
        curve2.setBorder(null);
        curve2.setBorderPainted(false);
        curve2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve2ActionPerformed(evt);
            }
        });

        curve3.setBackground(new java.awt.Color(6, 12, 223));
        curve3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve3.setForeground(new java.awt.Color(255, 255, 255));
        curve3.setText("300");
        curve3.setBorder(null);
        curve3.setBorderPainted(false);
        curve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve3ActionPerformed(evt);
            }
        });

        curve4.setBackground(new java.awt.Color(6, 12, 223));
        curve4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve4.setForeground(new java.awt.Color(255, 255, 255));
        curve4.setText("400");
        curve4.setBorder(null);
        curve4.setBorderPainted(false);
        curve4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve4ActionPerformed(evt);
            }
        });

        curveLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curveLabel.setText("Curve Sketching");

        curve5.setBackground(new java.awt.Color(6, 12, 223));
        curve5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve5.setForeground(new java.awt.Color(255, 255, 255));
        curve5.setText("500");
        curve5.setBorder(null);
        curve5.setBorderPainted(false);
        curve5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve5ActionPerformed(evt);
            }
        });

        curve1.setBackground(new java.awt.Color(6, 12, 223));
        curve1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve1.setForeground(new java.awt.Color(255, 255, 255));
        curve1.setText("100");
        curve1.setBorder(null);
        curve1.setBorderPainted(false);
        curve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve1ActionPerformed(evt);
            }
        });

        hop2.setBackground(new java.awt.Color(6, 12, 223));
        hop2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop2.setForeground(new java.awt.Color(255, 255, 255));
        hop2.setText("200");
        hop2.setBorder(null);
        hop2.setBorderPainted(false);
        hop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop2ActionPerformed(evt);
            }
        });

        hop3.setBackground(new java.awt.Color(6, 12, 223));
        hop3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop3.setForeground(new java.awt.Color(255, 255, 255));
        hop3.setText("300");
        hop3.setBorder(null);
        hop3.setBorderPainted(false);
        hop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop3ActionPerformed(evt);
            }
        });

        hop4.setBackground(new java.awt.Color(6, 12, 223));
        hop4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop4.setForeground(new java.awt.Color(255, 255, 255));
        hop4.setText("400");
        hop4.setBorder(null);
        hop4.setBorderPainted(false);
        hop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop4ActionPerformed(evt);
            }
        });

        hopLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hopLabel.setText("L'Hopitals Rule");

        hop5.setBackground(new java.awt.Color(6, 12, 223));
        hop5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop5.setForeground(new java.awt.Color(255, 255, 255));
        hop5.setText("500");
        hop5.setBorder(null);
        hop5.setBorderPainted(false);
        hop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop5ActionPerformed(evt);
            }
        });

        hop1.setBackground(new java.awt.Color(6, 12, 223));
        hop1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop1.setForeground(new java.awt.Color(255, 255, 255));
        hop1.setText("100");
        hop1.setBorder(null);
        hop1.setBorderPainted(false);
        hop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop1ActionPerformed(evt);
            }
        });

        int2.setBackground(new java.awt.Color(6, 12, 223));
        int2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int2.setForeground(new java.awt.Color(255, 255, 255));
        int2.setText("200");
        int2.setBorder(null);
        int2.setBorderPainted(false);
        int2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int2ActionPerformed(evt);
            }
        });

        int3.setBackground(new java.awt.Color(6, 12, 223));
        int3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int3.setForeground(new java.awt.Color(255, 255, 255));
        int3.setText("300");
        int3.setBorder(null);
        int3.setBorderPainted(false);
        int3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int3ActionPerformed(evt);
            }
        });

        int4.setBackground(new java.awt.Color(6, 12, 223));
        int4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int4.setForeground(new java.awt.Color(255, 255, 255));
        int4.setText("400");
        int4.setBorder(null);
        int4.setBorderPainted(false);
        int4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int4ActionPerformed(evt);
            }
        });

        intLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        intLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intLabel.setText("Integration");

        int5.setBackground(new java.awt.Color(6, 12, 223));
        int5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int5.setForeground(new java.awt.Color(255, 255, 255));
        int5.setText("500");
        int5.setBorder(null);
        int5.setBorderPainted(false);
        int5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int5ActionPerformed(evt);
            }
        });

        int1.setBackground(new java.awt.Color(6, 12, 223));
        int1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int1.setForeground(new java.awt.Color(255, 255, 255));
        int1.setText("100");
        int1.setBorder(null);
        int1.setBorderPainted(false);
        int1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int1ActionPerformed(evt);
            }
        });

        player1Label.setEditable(false);
        player1Label.setBackground(new java.awt.Color(230, 255, 251));
        player1Label.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player1Label.setText("Player 1 Score: " + String.valueOf(playerScores[0])
        );

        player2Label.setEditable(false);
        player2Label.setBackground(new java.awt.Color(255, 230, 234));
        player2Label.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player2Label.setText("Player 2 Score: " + String.valueOf(playerScores[1])
        );

        answerField.setForeground(new java.awt.Color(125, 125, 125));
        answerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerField.setToolTipText("");
        answerField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answerField.setName(""); // NOI18N

        check.setBackground(new java.awt.Color(204, 255, 204));
        check.setText("Check");
        check.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        check.setBorderPainted(false);
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText(" ");

        turnLabel.setBackground(new java.awt.Color(230, 255, 251));
        turnLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        turnLabel.setForeground(new java.awt.Color(6, 12, 223));
        turnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnLabel.setText("Player " + turn + "'s Turn");
        turnLabel.setOpaque(true);

        questionLabel.setEditable(false);
        questionLabel.setBackground(new java.awt.Color(6, 12, 223));
        questionLabel.setColumns(20);
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setLineWrap(true);
        questionLabel.setRows(5);
        questionLabel.setText("  1. Select a question.\n  2. The question will appear at the bottom (here). \n  3. "
            + "Type your answer with two decimal places, even if the answer is a whole \n      number. Assume radians "
            + "for trigonometric functions.\n  4. Now it's the next player's turn.");
        questionLabel.setWrapStyleWord(true);
        jScrollPane1.setViewportView(questionLabel);

        help.setBackground(new java.awt.Color(204, 255, 204));
        help.setText("Help");
        help.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        help.setBorderPainted(false);
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        restart.setBackground(new java.awt.Color(204, 255, 204));
        restart.setText("Restart");
        restart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        restart.setBorderPainted(false);
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        creditsLabel.setBackground(new java.awt.Color(204, 255, 204));
        creditsLabel.setText("Credits");
        creditsLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        creditsLabel.setBorderPainted(false);
        creditsLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diff1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(curve1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(int1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(turnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(help)
                            .addComponent(restart)
                            .addComponent(creditsLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(turnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vect1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diff1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(curveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(curve1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hop1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(int1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerField, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect1ActionPerformed
        if(vectPressed[0] == false){  
            questionType = "Vect";
            ptsAdded = 100;
            showQuestion();
            vect1.setBackground(Color.white);
            vectPressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect1ActionPerformed

    private void vect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect2ActionPerformed
        if(vectPressed[1] == false){  
            questionType = "Vect";
            ptsAdded = 200;
            showQuestion();
            vect2.setBackground(Color.white);
            vectPressed[1] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect2ActionPerformed

    private void vect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect3ActionPerformed
        if(vectPressed[2] == false){  
            questionType = "Vect";
            ptsAdded = 300;
            showQuestion();
            vect3.setBackground(Color.white);
            vectPressed[2] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect3ActionPerformed

    private void vect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect4ActionPerformed
        if(vectPressed[3] == false){  
            questionType = "Vect";
            ptsAdded = 400;
            showQuestion();
            vect4.setBackground(Color.white);
            vectPressed[3] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect4ActionPerformed

    private void vect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect5ActionPerformed
        if(vectPressed[4] == false){  
            questionType = "Vect";
            ptsAdded = 500;
            showQuestion();
            vect5.setBackground(Color.white);
            vectPressed[4] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect5ActionPerformed

    private void diff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff2ActionPerformed
        if(diffPressed[1] == false){  
            questionType = "Diff";
            ptsAdded = 200;
            showQuestion();
            diff2.setBackground(Color.white);
            diffPressed[1] = true;
            questionType = "";
        }
    }//GEN-LAST:event_diff2ActionPerformed

    private void diff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff3ActionPerformed
        if(diffPressed[2] == false){  
            questionType = "Diff";
            ptsAdded = 300;
            showQuestion();
            diff3.setBackground(Color.white);
            diffPressed[2] = true;
            questionType = "";
        }
    }//GEN-LAST:event_diff3ActionPerformed

    private void diff4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff4ActionPerformed
        if(diffPressed[3] == false){  
            questionType = "Diff";
            ptsAdded = 400;
            showQuestion();
            diff4.setBackground(Color.white);
            diffPressed[3] = true;
            questionType = "";
        }
    }//GEN-LAST:event_diff4ActionPerformed

    private void diff5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff5ActionPerformed
        if(diffPressed[4] == false){  
            questionType = "Diff";
            ptsAdded = 500;
            showQuestion();
            diff5.setBackground(Color.white);
            diffPressed[4] = true;
            questionType = "";
        }
    }//GEN-LAST:event_diff5ActionPerformed

    private void diff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff1ActionPerformed
        if(diffPressed[0] == false){  
            questionType = "Diff";
            ptsAdded = 100;
            showQuestion();
            diff1.setBackground(Color.white);
            diffPressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_diff1ActionPerformed

    private void curve2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve2ActionPerformed
        if(curvePressed[1] == false){  
            questionType = "Curve";
            ptsAdded = 200;
            showQuestion();
            curve2.setBackground(Color.white);
            curvePressed[1] = true;
            questionType = "";
        }
    }//GEN-LAST:event_curve2ActionPerformed

    private void curve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve3ActionPerformed
        if(curvePressed[2] == false){  
            questionType = "Curve";
            ptsAdded = 300;
            showQuestion();
            curve3.setBackground(Color.white);
            curvePressed[2] = true;
            questionType = "";
        }
    }//GEN-LAST:event_curve3ActionPerformed

    private void curve4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve4ActionPerformed
        if(curvePressed[3] == false){  
            questionType = "Curve";
            ptsAdded = 400;
            showQuestion();
            curve4.setBackground(Color.white);
            curvePressed[3] = true;
            questionType = "";
        }
    }//GEN-LAST:event_curve4ActionPerformed

    private void curve5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve5ActionPerformed
        if(curvePressed[4] == false){  
            questionType = "Curve";
            ptsAdded = 500;
            showQuestion();
            curve5.setBackground(Color.white);
            curvePressed[4] = true;
            questionType = "";
        }
    }//GEN-LAST:event_curve5ActionPerformed

    private void curve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve1ActionPerformed
        if(curvePressed[0] == false){  
            questionType = "Curve";
            ptsAdded = 100;
            showQuestion();
            curve1.setBackground(Color.white);
            curvePressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_curve1ActionPerformed

    private void hop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop2ActionPerformed
        if(hopPressed[1] == false){  
            questionType = "LHopital";
            ptsAdded = 200;
            showQuestion();
            hop2.setBackground(Color.white);
            hopPressed[1] = true;
            questionType = "";
        }
    }//GEN-LAST:event_hop2ActionPerformed

    private void hop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop3ActionPerformed
        if(hopPressed[2] == false){  
            questionType = "LHopital";
            ptsAdded = 300;
            showQuestion();
            hop3.setBackground(Color.white);
            hopPressed[2] = true;
            questionType = "";
        }
    }//GEN-LAST:event_hop3ActionPerformed

    private void hop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop4ActionPerformed
        if(hopPressed[3] == false){  
            questionType = "LHopital";
            ptsAdded = 400;
            showQuestion();
            hop4.setBackground(Color.white);
            hopPressed[3] = true;
            questionType = "";
        }
    }//GEN-LAST:event_hop4ActionPerformed

    private void hop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop5ActionPerformed
        if(hopPressed[4] == false){  
            questionType = "LHopital";
            ptsAdded = 500;
            showQuestion();
            hop5.setBackground(Color.white);
            hopPressed[4] = true;
            questionType = "";
        }
    }//GEN-LAST:event_hop5ActionPerformed

    private void hop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop1ActionPerformed
        if(hopPressed[0] == false){  
            questionType = "LHopital";
            ptsAdded = 100;
            showQuestion();
            hop1.setBackground(Color.white);
            hopPressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_hop1ActionPerformed

    private void int2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int2ActionPerformed
        if(intPressed[1] == false){  
            questionType = "Int";
            ptsAdded = 200;
            showQuestion();
            int2.setBackground(Color.white);
            intPressed[1] = true;
            questionType = "";
        }
    }//GEN-LAST:event_int2ActionPerformed

    private void int3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int3ActionPerformed
        if(intPressed[2] == false){  
            questionType = "Int";
            ptsAdded = 300;
            showQuestion();
            int3.setBackground(Color.white);
            intPressed[2] = true;
            questionType = "";
        }
    }//GEN-LAST:event_int3ActionPerformed

    private void int4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int4ActionPerformed
        if(intPressed[3] == false){  
            questionType = "Int";
            ptsAdded = 400;
            showQuestion();
            int4.setBackground(Color.white);
            intPressed[3] = true;
            questionType = "";
        }
    }//GEN-LAST:event_int4ActionPerformed

    private void int5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int5ActionPerformed
        if(intPressed[4] == false){  
            questionType = "Int";
            ptsAdded = 500;
            showQuestion();
            int5.setBackground(Color.white);
            intPressed[4] = true;
            questionType = "";
        }
    }//GEN-LAST:event_int5ActionPerformed

    private void int1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int1ActionPerformed
        if(intPressed[0] == false){  
            questionType = "Int";
            ptsAdded = 100;
            showQuestion();
            int1.setBackground(Color.white);
            intPressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_int1ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // Get the user's answer
        try {
            double answer = Double.parseDouble(answerField.getText().trim());
            answer = Math.round(answer*100.0)/100.0;

            // Get the correct answer from the check button's client property
            double correctAnswer = (double) check.getClientProperty("correctAnswer");
            correctAnswer = Math.round(correctAnswer*100.0)/100.0;

            if (answer == correctAnswer) {
                resultLabel.setText("Correct!");

                if(turn == 1) {
                      playerScores[turn-1] += ptsAdded;
                      player1Label.setText("Player 1 Score: " + String.valueOf(playerScores[turn-1]));
                      player1Label.repaint();
                } else if (turn == 2) {
                      playerScores[turn-1] += ptsAdded;
                      player2Label.setText("Player 2 Score: " + String.valueOf(playerScores[turn-1]));
                      player2Label.repaint();
                }
            } else {
                resultLabel.setText("Incorrect. Answer: " + correctAnswer);
            }
            
            ptsAdded = 0;
            changeTurn();
            
            answerField.setText("");
        } catch (Exception e){System.out.println(e);}
    }//GEN-LAST:event_checkActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        vectPressed = new boolean[5];
        diffPressed = new boolean[5];
        curvePressed = new boolean[5];
        hopPressed = new boolean[5];
        intPressed = new boolean[5];
        
        ptsAdded = 0;
        questionType = "";
        
        turn = 1;
        
        playerScores = new int[numPlayers];
        
        Color jeopardy = new Color(6,12,223);
        vect1.setBackground(jeopardy);
        vect2.setBackground(jeopardy);
        vect3.setBackground(jeopardy);
        vect4.setBackground(jeopardy);
        vect5.setBackground(jeopardy);
        
        diff1.setBackground(jeopardy);
        diff2.setBackground(jeopardy);
        diff3.setBackground(jeopardy);
        diff4.setBackground(jeopardy);
        diff5.setBackground(jeopardy);
        
        curve1.setBackground(jeopardy);
        curve2.setBackground(jeopardy);
        curve3.setBackground(jeopardy);
        curve4.setBackground(jeopardy);
        curve5.setBackground(jeopardy);
        
        hop1.setBackground(jeopardy);
        hop2.setBackground(jeopardy);
        hop3.setBackground(jeopardy);
        hop4.setBackground(jeopardy);
        hop5.setBackground(jeopardy);
        
        int1.setBackground(jeopardy);
        int2.setBackground(jeopardy);
        int3.setBackground(jeopardy);
        int4.setBackground(jeopardy);
        int5.setBackground(jeopardy);
        
        player1Label.setText("Player 1 Score: 0");
        player2Label.setText("Player 2 Score: 0");
        turnLabel.setText("Player 1's Turn");
        turnLabel.setBackground(new Color(230,255,251));
        questionLabel.setText("  1. Select a question.\n  2. The question will appear at the bottom (here). \n  3. "
                + "Type your answer with two decimal places, even if the answer is a whole \n      number. Assume radians "
                + "for trigonometric functions.\n  4. Now it's the next player's turn.");
        this.repaint();
    }//GEN-LAST:event_restartActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        questionLabel.setText("  1. Select a question.\n  2. The question will appear at the bottom (here). \n  3. "
                + "Type your answer with two decimal places, even if the answer is a whole \n      number. Assume radians "
                + "for trigonometric functions.\n  4. Now it's the next player's turn.");
    }//GEN-LAST:event_helpActionPerformed

    private void creditsLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsLabelActionPerformed
        questionLabel.setText("  Names: Ishan Garg, Pranav Mahabal, and Krish Patel. \n  Course: MCV4U0-1\n  Date: January 9, 2023\n  Teacher: Ms. Iulia Gugoiu");
    }//GEN-LAST:event_creditsLabelActionPerformed
    
    private void showQuestion() {
        String question = "";
        double correctAnswer = 0.0;
        
        this.repaint();
        turnLabel.repaint();
        switch (questionType) {
            case "Vect" -> {
                question = vectQ.getQuestion(ptsAdded);
                correctAnswer = vectQ.getCorrectAns();
            }
            case "Diff" -> {
                question = diffQ.getQuestion(ptsAdded);
                correctAnswer = diffQ.getCorrectAns();
            }
            case "Curve" -> {
                question = curveQ.getQuestion(ptsAdded);
                correctAnswer = curveQ.getCorrectAns();
            }
            case "LHopital" -> {
                question = hopQ.getQuestion(ptsAdded);
                correctAnswer = hopQ.getCorrectAns();
            }
            case "Int" -> {
                question = intQ.getQuestion(ptsAdded);
                correctAnswer = intQ.getCorrectAns();
            }
        }
        
        questionLabel.setText(question);
        check.putClientProperty("correctAnswer", correctAnswer);
    }
    
    private void changeTurn() {
        turn++;
        if(turn > numPlayers) {
            turn = 1;
        }
        turnLabel.setText("Player " + turn + "'s Turn");
        if(turn == 1) {
            turnLabel.setBackground(new Color(230,255,251));
        } else if(turn == 2) {
            turnLabel.setBackground(new Color(255,230,234));
        }
        turnLabel.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField answerField;
    private javax.swing.JButton check;
    private javax.swing.JButton creditsLabel;
    private javax.swing.JButton curve1;
    private javax.swing.JButton curve2;
    private javax.swing.JButton curve3;
    private javax.swing.JButton curve4;
    private javax.swing.JButton curve5;
    private javax.swing.JLabel curveLabel;
    private javax.swing.JButton diff1;
    private javax.swing.JButton diff2;
    private javax.swing.JButton diff3;
    private javax.swing.JButton diff4;
    private javax.swing.JButton diff5;
    private javax.swing.JLabel diffLabel;
    private javax.swing.JButton help;
    private javax.swing.JButton hop1;
    private javax.swing.JButton hop2;
    private javax.swing.JButton hop3;
    private javax.swing.JButton hop4;
    private javax.swing.JButton hop5;
    private javax.swing.JLabel hopLabel;
    private javax.swing.JButton int1;
    private javax.swing.JButton int2;
    private javax.swing.JButton int3;
    private javax.swing.JButton int4;
    private javax.swing.JButton int5;
    private javax.swing.JLabel intLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JTextField player1Label;
    private javax.swing.JTextField player2Label;
    private javax.swing.JTextArea questionLabel;
    private javax.swing.JButton restart;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel turnLabel;
    private javax.swing.JButton vect1;
    private javax.swing.JButton vect2;
    private javax.swing.JButton vect3;
    private javax.swing.JButton vect4;
    private javax.swing.JButton vect5;
    private javax.swing.JLabel vectLabel;
    // End of variables declaration//GEN-END:variables
}
