
import java.awt.*;
import java.util.Random;
import javax.swing.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ishu
 */
public class AskQuestion extends javax.swing.JDialog {

    private int player1Score;
    private int player2Score;
    private boolean[] vectPressed;
    private String questionType;
    private int ptsAdded;
    
    /**
     * Creates new form AskQuestion
     */
    public AskQuestion(java.awt.Frame parent, boolean modal, int p1Score, int p2Score) {
        super(parent, modal);
        initComponents();
        this.player1Score = p1Score;
        this.player2Score = p2Score;
        vectPressed = new boolean[5];
        ptsAdded = 0;
        questionType = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        vect1 = new javax.swing.JButton();
        menuTitle = new javax.swing.JLabel();
        vect2 = new javax.swing.JButton();
        vect3 = new javax.swing.JButton();
        vect4 = new javax.swing.JButton();
        vect5 = new javax.swing.JButton();
        vectLabel = new javax.swing.JLabel();
        diff2 = new javax.swing.JButton();
        diff3 = new javax.swing.JButton();
        diff4 = new javax.swing.JButton();
        diffLabel = new javax.swing.JLabel();
        diff5 = new javax.swing.JButton();
        diff1 = new javax.swing.JButton();
        curve2 = new javax.swing.JButton();
        curve3 = new javax.swing.JButton();
        curve4 = new javax.swing.JButton();
        curveLabel = new javax.swing.JLabel();
        curve5 = new javax.swing.JButton();
        curve1 = new javax.swing.JButton();
        hop2 = new javax.swing.JButton();
        hop3 = new javax.swing.JButton();
        hop4 = new javax.swing.JButton();
        hopLabel = new javax.swing.JLabel();
        hop5 = new javax.swing.JButton();
        hop1 = new javax.swing.JButton();
        int2 = new javax.swing.JButton();
        int3 = new javax.swing.JButton();
        int4 = new javax.swing.JButton();
        intLabel = new javax.swing.JLabel();
        int5 = new javax.swing.JButton();
        int1 = new javax.swing.JButton();
        player1Label = new javax.swing.JTextField();
        player2Label = new javax.swing.JTextField();
        questionLabel = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        check = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        vect1.setBackground(new java.awt.Color(6, 12, 223));
        vect1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect1.setForeground(new java.awt.Color(255, 255, 255));
        vect1.setText("100");
        vect1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        vect1.setBorderPainted(false);
        vect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect1ActionPerformed(evt);
            }
        });

        menuTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("Calculus Jeopardy");
        menuTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        vect2.setBackground(new java.awt.Color(6, 12, 223));
        vect2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect2.setForeground(new java.awt.Color(255, 255, 255));
        vect2.setText("200");
        vect2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        vect2.setBorderPainted(false);
        vect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect2ActionPerformed(evt);
            }
        });

        vect3.setBackground(new java.awt.Color(6, 12, 223));
        vect3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect3.setForeground(new java.awt.Color(255, 255, 255));
        vect3.setText("300");
        vect3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        vect3.setBorderPainted(false);
        vect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect3ActionPerformed(evt);
            }
        });

        vect4.setBackground(new java.awt.Color(6, 12, 223));
        vect4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect4.setForeground(new java.awt.Color(255, 255, 255));
        vect4.setText("400");
        vect4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        vect4.setBorderPainted(false);
        vect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect4ActionPerformed(evt);
            }
        });

        vect5.setBackground(new java.awt.Color(6, 12, 223));
        vect5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vect5.setForeground(new java.awt.Color(255, 255, 255));
        vect5.setText("500");
        vect5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        vect5.setBorderPainted(false);
        vect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vect5ActionPerformed(evt);
            }
        });

        vectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vectLabel.setText("Vectors");

        diff2.setBackground(new java.awt.Color(6, 12, 223));
        diff2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff2.setForeground(new java.awt.Color(255, 255, 255));
        diff2.setText("200");
        diff2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        diff2.setBorderPainted(false);
        diff2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff2ActionPerformed(evt);
            }
        });

        diff3.setBackground(new java.awt.Color(6, 12, 223));
        diff3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff3.setForeground(new java.awt.Color(255, 255, 255));
        diff3.setText("300");
        diff3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        diff3.setBorderPainted(false);
        diff3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff3ActionPerformed(evt);
            }
        });

        diff4.setBackground(new java.awt.Color(6, 12, 223));
        diff4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff4.setForeground(new java.awt.Color(255, 255, 255));
        diff4.setText("400");
        diff4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        diff4.setBorderPainted(false);
        diff4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff4ActionPerformed(evt);
            }
        });

        diffLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diffLabel.setText("Differentiation");

        diff5.setBackground(new java.awt.Color(6, 12, 223));
        diff5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff5.setForeground(new java.awt.Color(255, 255, 255));
        diff5.setText("500");
        diff5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        diff5.setBorderPainted(false);
        diff5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff5ActionPerformed(evt);
            }
        });

        diff1.setBackground(new java.awt.Color(6, 12, 223));
        diff1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diff1.setForeground(new java.awt.Color(255, 255, 255));
        diff1.setText("100");
        diff1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        diff1.setBorderPainted(false);
        diff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diff1ActionPerformed(evt);
            }
        });

        curve2.setBackground(new java.awt.Color(6, 12, 223));
        curve2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve2.setForeground(new java.awt.Color(255, 255, 255));
        curve2.setText("200");
        curve2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        curve2.setBorderPainted(false);
        curve2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve2ActionPerformed(evt);
            }
        });

        curve3.setBackground(new java.awt.Color(6, 12, 223));
        curve3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve3.setForeground(new java.awt.Color(255, 255, 255));
        curve3.setText("300");
        curve3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        curve3.setBorderPainted(false);
        curve3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve3ActionPerformed(evt);
            }
        });

        curve4.setBackground(new java.awt.Color(6, 12, 223));
        curve4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve4.setForeground(new java.awt.Color(255, 255, 255));
        curve4.setText("400");
        curve4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        curve4.setBorderPainted(false);
        curve4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve4ActionPerformed(evt);
            }
        });

        curveLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        curveLabel.setText("Curve Sketching");

        curve5.setBackground(new java.awt.Color(6, 12, 223));
        curve5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve5.setForeground(new java.awt.Color(255, 255, 255));
        curve5.setText("500");
        curve5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        curve5.setBorderPainted(false);
        curve5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve5ActionPerformed(evt);
            }
        });

        curve1.setBackground(new java.awt.Color(6, 12, 223));
        curve1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        curve1.setForeground(new java.awt.Color(255, 255, 255));
        curve1.setText("100");
        curve1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        curve1.setBorderPainted(false);
        curve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curve1ActionPerformed(evt);
            }
        });

        hop2.setBackground(new java.awt.Color(6, 12, 223));
        hop2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop2.setForeground(new java.awt.Color(255, 255, 255));
        hop2.setText("200");
        hop2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        hop2.setBorderPainted(false);
        hop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop2ActionPerformed(evt);
            }
        });

        hop3.setBackground(new java.awt.Color(6, 12, 223));
        hop3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop3.setForeground(new java.awt.Color(255, 255, 255));
        hop3.setText("300");
        hop3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        hop3.setBorderPainted(false);
        hop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop3ActionPerformed(evt);
            }
        });

        hop4.setBackground(new java.awt.Color(6, 12, 223));
        hop4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop4.setForeground(new java.awt.Color(255, 255, 255));
        hop4.setText("400");
        hop4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        hop4.setBorderPainted(false);
        hop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop4ActionPerformed(evt);
            }
        });

        hopLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hopLabel.setText("L'Hopitals Rule");

        hop5.setBackground(new java.awt.Color(6, 12, 223));
        hop5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop5.setForeground(new java.awt.Color(255, 255, 255));
        hop5.setText("500");
        hop5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        hop5.setBorderPainted(false);
        hop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop5ActionPerformed(evt);
            }
        });

        hop1.setBackground(new java.awt.Color(6, 12, 223));
        hop1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hop1.setForeground(new java.awt.Color(255, 255, 255));
        hop1.setText("100");
        hop1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        hop1.setBorderPainted(false);
        hop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hop1ActionPerformed(evt);
            }
        });

        int2.setBackground(new java.awt.Color(6, 12, 223));
        int2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int2.setForeground(new java.awt.Color(255, 255, 255));
        int2.setText("200");
        int2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        int2.setBorderPainted(false);
        int2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int2ActionPerformed(evt);
            }
        });

        int3.setBackground(new java.awt.Color(6, 12, 223));
        int3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int3.setForeground(new java.awt.Color(255, 255, 255));
        int3.setText("300");
        int3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        int3.setBorderPainted(false);
        int3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int3ActionPerformed(evt);
            }
        });

        int4.setBackground(new java.awt.Color(6, 12, 223));
        int4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int4.setForeground(new java.awt.Color(255, 255, 255));
        int4.setText("400");
        int4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        int4.setBorderPainted(false);
        int4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int4ActionPerformed(evt);
            }
        });

        intLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        intLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intLabel.setText("Integration");

        int5.setBackground(new java.awt.Color(6, 12, 223));
        int5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int5.setForeground(new java.awt.Color(255, 255, 255));
        int5.setText("500");
        int5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        int5.setBorderPainted(false);
        int5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int5ActionPerformed(evt);
            }
        });

        int1.setBackground(new java.awt.Color(6, 12, 223));
        int1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        int1.setForeground(new java.awt.Color(255, 255, 255));
        int1.setText("100");
        int1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(6, 12, 223), 1, true));
        int1.setBorderPainted(false);
        int1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int1ActionPerformed(evt);
            }
        });

        player1Label.setEditable(false);
        player1Label.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player1Label.setText("Player 1 Score: " + String.valueOf(player1Score)
        );
        player1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1LabelActionPerformed(evt);
            }
        });

        player2Label.setEditable(false);
        player2Label.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        player2Label.setText("Player 2 Score: " + String.valueOf(player2Score)
        );
        player2Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2LabelActionPerformed(evt);
            }
        });

        questionLabel.setBackground(new java.awt.Color(6, 12, 223));
        questionLabel.setForeground(new java.awt.Color(255, 255, 255));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        questionLabel.setText(" ");
        questionLabel.setOpaque(true);

        answerField.setForeground(new java.awt.Color(125, 125, 125));
        answerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answerField.setToolTipText("");
        answerField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        answerField.setName(""); // NOI18N

        check.setText("Check");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vect5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diff1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diff5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(curve1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curve5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hop1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(int1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(int5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(check)))
                        .addGap(60, 60, 60)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vect1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vect5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diff1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(curveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(curve1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(curve5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hop1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hop5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(int1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(int5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect1ActionPerformed
        if(vectPressed[0] == false){  
            questionType = "Vect";
            showQuestion();
            ptsAdded = 100;
            vect1.setBackground(Color.white);
            vectPressed[0] = true;
            questionType = "";
        }
    }//GEN-LAST:event_vect1ActionPerformed

    private void vect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vect2ActionPerformed

    private void vect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vect3ActionPerformed

    private void vect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vect4ActionPerformed

    private void vect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vect5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vect5ActionPerformed

    private void diff2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff2ActionPerformed

    private void diff3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff3ActionPerformed

    private void diff4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff4ActionPerformed

    private void diff5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff5ActionPerformed

    private void diff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diff1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diff1ActionPerformed

    private void curve2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curve2ActionPerformed

    private void curve3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curve3ActionPerformed

    private void curve4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curve4ActionPerformed

    private void curve5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curve5ActionPerformed

    private void curve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curve1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curve1ActionPerformed

    private void hop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hop2ActionPerformed

    private void hop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hop3ActionPerformed

    private void hop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hop4ActionPerformed

    private void hop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hop5ActionPerformed

    private void hop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hop1ActionPerformed

    private void int2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int2ActionPerformed

    private void int3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int3ActionPerformed

    private void int4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int4ActionPerformed

    private void int5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int5ActionPerformed

    private void int1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_int1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_int1ActionPerformed

    private void player1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1LabelActionPerformed

    private void player2LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2LabelActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // Get the user's answer
        int answer = Integer.parseInt(answerField.getText().trim());

        // Get the correct answer from the check button's client property
        int correctAnswer = (int) check.getClientProperty("correctAnswer");

        if (answer == correctAnswer) {
          resultLabel.setText("Correct!");
          
          player1Score += ptsAdded;
          player1Label.setText("Player 1 Score: " + String.valueOf(player1Score));
          player1Label.repaint();
          ptsAdded = 0;
          
        } else {
          resultLabel.setText("Incorrect. Answer: " + correctAnswer);
        }
        answerField.setText("");
    }//GEN-LAST:event_checkActionPerformed
    
    private void showQuestion() {
        VectorQuestions vectQ = new VectorQuestions();
        String question = "";
        int correctAnswer = 0;
        
        switch (questionType) {
            case "Vect":
                question = vectQ.getQuestion();
                correctAnswer = vectQ.getVectCorrectAns();
                break;
            case "Diff":
                
                break;
            case "Curve":
                
                break;
            case "L'Hopital":
                
                break;
          case "Int":
                
                break;
        }
        
        questionLabel.setText(question);
        check.putClientProperty("correctAnswer", correctAnswer);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField answerField;
    private javax.swing.JButton check;
    private javax.swing.JButton curve1;
    private javax.swing.JButton curve2;
    private javax.swing.JButton curve3;
    private javax.swing.JButton curve4;
    private javax.swing.JButton curve5;
    private javax.swing.JLabel curveLabel;
    private javax.swing.JButton diff1;
    private javax.swing.JButton diff2;
    private javax.swing.JButton diff3;
    private javax.swing.JButton diff4;
    private javax.swing.JButton diff5;
    private javax.swing.JLabel diffLabel;
    private javax.swing.JButton hop1;
    private javax.swing.JButton hop2;
    private javax.swing.JButton hop3;
    private javax.swing.JButton hop4;
    private javax.swing.JButton hop5;
    private javax.swing.JLabel hopLabel;
    private javax.swing.JButton int1;
    private javax.swing.JButton int2;
    private javax.swing.JButton int3;
    private javax.swing.JButton int4;
    private javax.swing.JButton int5;
    private javax.swing.JLabel intLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JTextField player1Label;
    private javax.swing.JTextField player2Label;
    javax.swing.JLabel questionLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton vect1;
    private javax.swing.JButton vect2;
    private javax.swing.JButton vect3;
    private javax.swing.JButton vect4;
    private javax.swing.JButton vect5;
    private javax.swing.JLabel vectLabel;
    // End of variables declaration//GEN-END:variables
}
